name: Spark Runner Nexmark
on:
  pull_request:
  schedule:
    - cron: '0 0 * * *' # Once per day at midnight
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner: [SparkRunner, SparkStructuredStreamingRunner]
        queryLanguage: [standard, sql]
      fail-fast: false
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Remove default github maven configuration
        # This step is a workaround to avoid a decryption issue of Beam's
        # net.linguica.gradle.maven.settings plugin and github's provided maven
        # settings.xml file
        run: rm ~/.m2/settings.xml
      - name: Checkout iemejia/ci-beam
        uses: actions/checkout@v2
      - name: Checkout apache/beam
        uses: actions/checkout@v2
        with:
          repository: apache/beam
          ref: master
          path: beam
      - name: Run Nexmark
        working-directory: beam
        run: ./gradlew :sdks:java:testing:nexmark:run
          -Pnexmark.runner=":runners:spark"
          -Pnexmark.args="
          --runner=${{ matrix.runner }}
          --streaming=false
          --suite=SMOKE
          --skipQueries=3
          --queryLanguage=${{ matrix.queryLanguage }}
          --manageResources=false
          --monitorJobs=true
          --enforceEncodability=true
          --enforceImmutability=true"
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: apache-slack-notification-test
          SLACK_COLOR: '#FF3333'
          SLACK_MESSAGE: Spark Runner Nexmark
          SLACK_TITLE: iemejia/ci-beam
          SLACK_USERNAME: iemejia/ci-beam
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
