name: Spark 3 Nexmark Java 8
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * *' # Once per day at midnight
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner: [SparkRunner, SparkStructuredStreamingRunner]
        queryLanguage: [standard, sql]
      fail-fast: false
    steps:
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Remove default github maven configuration
        # This step is a workaround to avoid a decryption issue of Beam's
        # net.linguica.gradle.maven.settings plugin and github's provided maven
        # settings.xml file
        run: rm ~/.m2/settings.xml
      - name: Checkout iemejia/ci-beam
        uses: actions/checkout@v2
      - name: Checkout iemejia/beam:BEAM-7092-spark3
        uses: actions/checkout@v2
        with:
          repository: iemejia/beam
          ref: BEAM-7092-spark3
          path: iemejia/beam
      - name: Run Spark 3 Nexmark Java 8
        working-directory: iemejia/beam
        run: ./gradlew :sdks:java:testing:nexmark:run
          -Pnexmark.runner=":runners:spark"
          -Pnexmark.args="
          --runner=SparkRunner
          --streaming=false
          --suite=SMOKE
          --queryLanguage=${{ matrix.queryLanguage }}
          --manageResources=false
          --monitorJobs=true
          --enforceEncodability=true
          --enforceImmutability=true"
