name: Spark 3 Runner Java 11
on:
  push:
  schedule:
    - cron: '0 0 * * *' # Once per day at midnight
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout iemejia/docker-beam-spark3
        uses: actions/checkout@v2
      - name: Run docker image
        run:
          docker build -t iemejia/beam:BEAM-7092-spark3 -f spark3/Dockerfile spark3
